"""
Django settings for cyberenigma_web project.
Generated by 'django-admin startproject' using Django 4.2.21.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-rqud(v_^60#ucbj7)@_po$_w_ijy-^!=+akjg$4w19bmqf0sv4')

# SECURITY WARNING: don't run with debug turned on in production!
# Set to True for development to get detailed error pages and enable static file serving.
DEBUG = True

LOGIN_REDIRECT_URL = '/member/'

# Get the Railway environment URL
RAILWAY_ENVIRONMENT = os.environ.get('RAILWAY_ENVIRONMENT', '')
RAILWAY_SERVICE_URL = os.environ.get('RAILWAY_STATIC_URL', '')

# Set allowed hosts
if RAILWAY_ENVIRONMENT:
    ALLOWED_HOSTS = [RAILWAY_ENVIRONMENT, 'localhost', '127.0.0.1']
    if RAILWAY_SERVICE_URL:
        ALLOWED_HOSTS.append(RAILWAY_SERVICE_URL.split('//')[-1].split('/')[0])
else:
    ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',  # Deine App
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- HIER EINFÜGEN
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cyberenigma_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # optional: BASE_DIR / "templates" falls Templates außerhalb von Apps
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cyberenigma_web.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# This is where Django will collect all static files for production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# This tells Django where to look for static files in development.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Simplified static file serving for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Für lokalen Proxy-Zugriff (Cascade, Browser-Preview)
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:64641",
]
